# Usa una imagen base de Alpine con PHP
FROM alpine:latest

# Establece la variable de entorno DEBIAN_FRONTEND en noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Actualiza los paquetes del sistema
RUN apk update

# Instala PHP y el servidor web ligero 'php-cli'
RUN apk add --no-cache php7-cli

# Copia los archivos del sitio web al directorio raíz del servidor web
COPY alpine/ /var/www/html

# Expone el puerto 80 para que sea accesible (opcional)
EXPOSE 80

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Inicia el servidor web incorporado de PHP
CMD php -S 0.0.0.0:80
