# Usa una imagen base de CentOS con PHP
FROM centos:latest

# Establece la variable de entorno DEBIAN_FRONTEND en noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# Actualiza los paquetes del sistema
RUN yum -y update

# Instala PHP y el servidor web ligero 'php-cli'
RUN yum -y install php-cli

# Copia los archivos del sitio web al directorio raíz del servidor web
COPY centos/ /var/www/html

# Expone el puerto 80 para que sea accesible (opcional)
EXPOSE 80

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Inicia el servidor web incorporado de PHP
CMD php -S 0.0.0.0:80

