# Usa una imagen base de Debian con PHP
FROM ubuntu:latest

# Actualiza los paquetes del sistema
RUN apt-get update

# Instala PHP y el servidor web ligero 'php-cli'
RUN apt-get install -y php-cli

# Copia los archivos del sitio web al directorio raíz del servidor web
COPY ubuntu/ /var/www/html

# Expone el puerto 80 para que sea accesible (opcional)
EXPOSE 80

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Inicia el servidor web incorporado de PHP
CMD php -S 0.0.0.0:80

