# Usa una imagen base de Debian
FROM debian:latest

# Actualiza los paquetes del sistema
RUN apt-get update

# Instala un servidor web (por ejemplo, Nginx)
RUN apt-get install -y nginx

# Copia los archivos del sitio web al directorio raíz del servidor web
COPY sitio_web/ /var/www/html

# Expone el puerto 80 para que sea accesible
EXPOSE 80

# Inicia el servidor web al iniciar el contenedor
CMD ["nginx", "-g", "daemon off;"]
