# Usa una imagen base de Debian
FROM debian:latest

# Actualiza los paquetes del sistema
RUN apt-get update

# Instala PHP y Nginx
RUN apt-get install -y php-fpm nginx

# Copia los archivos del sitio web al directorio raíz del servidor web
COPY debian/ /var/www/html

# Expone el puerto 80 para que sea accesible
EXPOSE 80

# Inicia PHP-FPM y Nginx al iniciar el contenedor
CMD service php7.4-fpm start && nginx -g "daemon off;"

